# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dev C
email: multijog2@naver.com
description: I Dreamed a Dream
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devchai.github.io" # the base hostname & protocol for your site
github_username:  devchai
paginate: 5
gems: [jekyll-paginate, kramdown, jekyll-sitemap]
plugins:
  - jekyll-sitemap
  - jekyll-paginate
# Build settings
markdown: kramdown
# Handling Reading
exclude : ["tmp"]
encoding:     "utf-8"
keep_files:   [".git", ".svn"]

